### ISSUE TITLE
this project can't compile

### ISSUE THREAD

**Issue by SunneeYang** [mafei198/game_server#1]
src/utils/record_mapper.erl:8: can't find include file "config_data_names.hrl"
src/utils/record_mapper.erl:9: can't find include file "db_table_names.hrl"
src/utils/record_mapper.erl:13: undefined macro 'DB_TABLE_NAMES'
src/utils/record_mapper.erl:14: undefined macro 'CONFIG_DATA_NAMES'
src/utils/record_mapper.erl:37: function info/2 undefined
Compiling src/utils/record_mapper.erl failed:
ERROR: compile failed while processing /Users/yangguang/my_game_server/game_server: rebar_abort

**Comment by mafei198** [comment]
@SunneeYang Can you scroll up and check the make logs, there should be some other errors occured. 
And please paste them to here.

**Comment by SunneeYang** [comment]
localhost:my_game_server yangguang$ make
./cmd install
./tools/install: line 37: bundle: command not found
./tools/install: line 38: bundle: command not found
==> ranch (get-deps)
==> sync (get-deps)
==> gproc (get-deps)
==> goldrush (get-deps)
==> lager (get-deps)
==> poolboy (get-deps)
==> eredis (get-deps)
==> timertask (get-deps)
==> leaderboard (get-deps)
==> chat_server (get-deps)
==> emysql (get-deps)
==> db (get-deps)
==> player_server (get-deps)
==> game_numerical (get-deps)
==> gen_smtp (get-deps)
==> apns (get-deps)
==> parse_trans (get-deps)
==> jsx (get-deps)
==> ibrowse (get-deps)
==> mtwist (get-deps)
==> eep (get-deps)
==> rel (get-deps)
==> game_server (get-deps)
==> game_server (clean)
==> ranch (compile)
==> sync (compile)
==> gproc (compile)
==> goldrush (compile)
==> lager (compile)
==> poolboy (compile)
==> eredis (compile)
==> timertask (compile)
==> leaderboard (compile)
==> chat_server (compile)
==> emysql (compile)
Generating "include/crypto_compat.hrl" ...
...supports cryto:hash/2
...no changes needed to "include/crypto_compat.hrl". Skipping writing new file
==> db (compile)
==> player_server (compile)
==> game_numerical (compile)
==> gen_smtp (compile)
==> apns (compile)
==> parse_trans (compile)
==> jsx (compile)
==> ibrowse (compile)
==> mtwist (compile)
==> eep (compile)
==> rel (compile)
==> game_server (compile)
Compiled src/utils/time_utils.erl
Compiled src/utils/sqerl.erl
Compiled src/utils/sqerl_tests.erl
src/utils/record_mapper.erl:6: can't find include file "db_schema.hrl"
src/utils/record_mapper.erl:8: can't find include file "config_data_names.hrl"
src/utils/record_mapper.erl:9: can't find include file "db_table_names.hrl"
src/utils/record_mapper.erl:13: undefined macro 'DB_TABLE_NAMES'
src/utils/record_mapper.erl:14: undefined macro 'CONFIG_DATA_NAMES'
src/utils/record_mapper.erl:37: function info/2 undefined
Compiling src/utils/record_mapper.erl failed:
ERROR: compile failed while processing /Users/yangguang/my_game_server/game_server: rebar_abort
localhost:my_game_server yangguang$ make clean
cd game_server && ./rebar clean
==> game_server (clean)
localhost:my_game_server yangguang$ make
./cmd install
./tools/install: line 37: bundle: command not found
./tools/install: line 38: bundle: command not found
==> ranch (get-deps)
==> sync (get-deps)
==> gproc (get-deps)
==> goldrush (get-deps)
==> lager (get-deps)
==> poolboy (get-deps)
==> eredis (get-deps)
==> timertask (get-deps)
==> leaderboard (get-deps)
==> chat_server (get-deps)
==> emysql (get-deps)
==> db (get-deps)
==> player_server (get-deps)
==> game_numerical (get-deps)
==> gen_smtp (get-deps)
==> apns (get-deps)
==> parse_trans (get-deps)
==> jsx (get-deps)
==> ibrowse (get-deps)
==> mtwist (get-deps)
==> eep (get-deps)
==> rel (get-deps)
==> game_server (get-deps)
==> game_server (clean)
==> ranch (compile)
==> sync (compile)
==> gproc (compile)
==> goldrush (compile)
==> lager (compile)
==> poolboy (compile)
==> eredis (compile)
==> timertask (compile)
==> leaderboard (compile)
==> chat_server (compile)
==> emysql (compile)
Generating "include/crypto_compat.hrl" ...
...supports cryto:hash/2
...no changes needed to "include/crypto_compat.hrl". Skipping writing new file
==> db (compile)
==> player_server (compile)
==> game_numerical (compile)
==> gen_smtp (compile)
==> apns (compile)
==> parse_trans (compile)
==> jsx (compile)
==> ibrowse (compile)
==> mtwist (compile)
==> eep (compile)
==> rel (compile)
==> game_server (compile)
Compiled src/utils/time_utils.erl
Compiled src/utils/sqerl.erl
Compiled src/utils/sqerl_tests.erl
Compiled src/utils/reloader.erl
src/utils/record_mapper.erl:6: can't find include file "db_schema.hrl"
src/utils/record_mapper.erl:8: can't find include file "config_data_names.hrl"
src/utils/record_mapper.erl:9: can't find include file "db_table_names.hrl"
src/utils/record_mapper.erl:13: undefined macro 'DB_TABLE_NAMES'
src/utils/record_mapper.erl:14: undefined macro 'CONFIG_DATA_NAMES'
src/utils/record_mapper.erl:37: function info/2 undefined
Compiling src/utils/record_mapper.erl failed:
ERROR: compile failed while processing /Users/yangguang/my_game_server/game_server: rebar_abort

**Comment by mafei198** [comment]
@SunneeYang you need to install Rails 3.2.9 and Ruby 1.9.3
